{
 "title": "XRCUBE",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[1] GPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(ping_avg_time[5m])"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total[5m])+rate(windows_net_bytes_sent_total[5m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "rate(windows_net_packets_outbound_errors_total[5m]) + rate(windows_net_packets_received_errors_total[5m])/ rate(windows_net_packets_total[5m])"
    }
   ]
  },
  {
   "title": "[1] GPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "avg_over_time(ping_avg_time[5m])"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total[5m])+rate(windows_net_bytes_sent_total[5m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "rate(windows_net_packets_outbound_errors_total[5m]) + rate(windows_net_packets_received_errors_total[5m])/ rate(windows_net_packets_total[5m])"
    }
   ]
  },
  {
   "title": "[1] GPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "avg_over_time(ping_avg_time[5m])"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total[5m])+rate(windows_net_bytes_sent_total[5m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "rate(windows_net_packets_outbound_errors_total[5m]) + rate(windows_net_packets_received_errors_total[5m])/ rate(windows_net_packets_total[5m])"
    }
   ]
  },
  {
   "title": "[1] GPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "avg_over_time(ping_avg_time[5m])"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total[5m])+rate(windows_net_bytes_sent_total[5m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "expr": "rate(windows_net_packets_outbound_errors_total[5m]) + rate(windows_net_packets_received_errors_total[5m])/ rate(windows_net_packets_total[5m])"
    }
   ]
  }
 ]
}